[package]
name = "prrng"
version = "0.2.0"
edition = "2024"
description = "psuedo-random number generation"
readme = "readme.md"
license = "Apache-2.0"
repository = "https://github.com/wainggan/prrng.git"

[dependencies]

